### ISSUE TITLE
Node rspec tests do not work with >= fog/1.16.0

### ISSUE THREAD

**Issue by chernjie** [rackspace/rumm#100]
Temporarily fixed in 71d4f1a as addressed by [this comment](https://github.com/rackspace/rumm/pull/99#issuecomment-75928221)

Steps to reproduce:
1) Change fog version to `~> 1.16` as shown below

```diff
diff --git rumm.gemspec rumm.gemspec
index 5358197..ceb669f 100644
--- rumm.gemspec
+++ rumm.gemspec
@@ -21,5 +21,5 @@ Gem::Specification.new do |spec|
   spec.required_ruby_version = ">= 1.9.3"

   spec.add_dependency "mvcli", "~> 0.0.16"
-  spec.add_dependency "fog", "1.16.0"
+  spec.add_dependency "fog", "~> 1.16"
 end
```

2)  run test for node

```bash
$ rspec spec/features/nodes_spec.rb

  An error occurred in an after hook
    NoMethodError: undefined method `[]' for nil:NilClass
    occurred at ~/workspace/rumm/spec/features/nodes_spec.rb:13:in `block (3 levels) in <top (required)>'

FFFF
```
